### ISSUE TITLE
Some valid `ignore`/`extend-ignore` codes are rejected when specified in config files

### ISSUE THREAD

**Issue by gschaffner** [PyCQA/flake8#1802] opened 2023-02-22 07:05 UTC
### how did you install flake8?

```console
$ pip install flake8
```

### unmodified output of `flake8 --bug-report`

```json
N/A (flake8 crashes before producing a report)
```

#### what i expected to happen

hi! i believe flake8 should not reject valid `ignore`/`extend-ignore` codes and code prefixes when they are provided via a config file instead of via `--ignore`/`--extend-ignore`.

#### sample code

```ini
# .flake8

[flake8]
ignore = ABC1234
```

#### commands ran

```console
$ flake8
Traceback (most recent call last):
  File "/tmp/tmp.CEuXC41pzp/.venv/bin/flake8", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/tmp/tmp.CEuXC41pzp/.venv/lib/python3.11/site-packages/flake8/main/cli.py", line 23, in main
    app.run(argv)
  File "/tmp/tmp.CEuXC41pzp/.venv/lib/python3.11/site-packages/flake8/main/application.py", line 198, in run
    self._run(argv)
  File "/tmp/tmp.CEuXC41pzp/.venv/lib/python3.11/site-packages/flake8/main/application.py", line 186, in _run
    self.initialize(argv)
  File "/tmp/tmp.CEuXC41pzp/.venv/lib/python3.11/site-packages/flake8/main/application.py", line 165, in initialize
    self.plugins, self.options = parse_args(argv)
                                 ^^^^^^^^^^^^^^^^
  File "/tmp/tmp.CEuXC41pzp/.venv/lib/python3.11/site-packages/flake8/options/parse_args.py", line 53, in parse_args
    opts = aggregator.aggregate_options(option_manager, cfg, cfg_dir, rest)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/tmp.CEuXC41pzp/.venv/lib/python3.11/site-packages/flake8/options/aggregator.py", line 30, in aggregate_options
    parsed_config = config.parse_config(manager, cfg, cfg_dir)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/tmp.CEuXC41pzp/.venv/lib/python3.11/site-packages/flake8/options/config.py", line 131, in parse_config
    raise ValueError(
ValueError: Error code 'ABC1234' supplied to 'ignore' option does not match '^[A-Z]{1,3}[0-9]{0,3}$'
```

note that using `--ignore=ABC1234` instead of using `ignore = ABC1234` in a config file works fine.

#### what i suspect to be the problem

the problem appears to be that the check https://github.com/PyCQA/flake8/blob/cb43b60dcc8ff6b20a5dc3f582ff599e1c1f9881/src/flake8/options/config.py#L128-L135

added in 1346ddefd315223b8f476bb02381a944e14f2cbc uses `VALID_CODE_PREFIX`, which ends in `$`. each entry in `ignore` must start with a valid code prefix, but i believe it doesn't need to *be* a valid code prefix; it can be longer.

(note: this issue is moot if flake8 requires that plugins only produce codes that match `^[A-Z]{1,3}[0-9]{0,3}$`. the docs note that entry point names are required to match `^[A-Z]{1,3}[0-9]{0,3}$`, but this restriction alone does not forbid things like:

*   a plugin that uses an entry point `ABC` and produces a code `ABC1234`. then `ignore = ABC1234` crashes flake8.
*   a plugin that uses an entry point `ABC` and produces a code `ABCD123`. then `ignore = ABCD123` crashes flake8.

as far as i found, the docs don't require plugins to only produce codes that match `^[A-Z]{1,3}[0-9]{0,3}$`, but it's possible the docs do specify this and i missed it. my apologies if that is the case.)

**Comment by sigmavirus24** [comment] 2023-02-22 12:59
Seems like a duplicate of #1777 and #1759

In the future, please search **closed and** open issues before creating new ones that are duplicates.

**Closed by sigmavirus24** 2023-02-22 12:59 UTC

**Comment by asottile** [comment] 2023-02-23 05:00
the error message is not wrong, why are you questioning it
